name: 11 - Working with Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
              description: '"Skip deployment and only print build output"'
              required: false
              type: boolean
            target:
              description: 'Environment to run tests against'
              type: environment
              required: true
            tag:
              description: 'Release from which to build and deploy'
              required: true
              default: 'v3'
              type: choice
              options:
              - v1
              - v2
              - v3
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Build
          run: |
            echo "Building from tag ${{ inputs.tag }}"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: ${{ inputs.target }}
        if: ${{ !inputs.dry-run }}
        steps:
        - name: Deploy
          run: |
            echo "Deploying to ${{ inputs.target }}"