name:
on:
    workflow_dispatch:
        inputs:
            build-status:
              type: choice
              default: 'success'
              required: true
              options:
              - success
              - failure

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.build.outputs.status }}
        steps:
        - name: Print GITHUB_OUTPUT path
          run: |
            echo "$GITHUB_OUTPUT"
        - name: Build
          id: build
          run: echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Deploy
          if: ${{ needs.build.outputs.output1 == 'success'}}
          run: echo "Deploying"