name:
on:
    workflow_dispatch:
        inputs:
            build-status:
              type: choice
              default: 'success'
              required: true
              options:
              - success
              - failure

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.build.outputs.status }}
            output2: ${{ steps.build.outputs.output2 }}
        steps:
        - name: Print GITHUB_OUTPUT path
          run: |
            echo "$GITHUB_OUTPUT"
        - name: Build
          id: build
          run: |
            echo "$GITHUB_OUTPUT" 
            echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
            echo "output2=value2" >> "$GITHUB_OUTPUT"
            echo "output3=value3" >> "$GITHUB_OUTPUT"
            cat "$GITHUB_OUTPUT"
        - name: Mistake
          run: |
            echo "mistake=true" > "$GITHUB_OUTPUT"
            cat "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Deploy
          if: ${{ needs.build.outputs.output1 == 'success'}}
          run: echo "Deploying"
        - name: Print Outputs
          run: |
            echo "Output-1: ${{ needs.build.outputs.output1 }}"